version: '3.4'

services:
  webapp:
    image: "pdp"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sql-server
      - redis

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "password"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
